project_id = "fkfdjibqpmdaobjrryja"

[functions.send-auth-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.youtube-oauth]
verify_jwt = false

[functions.tiktok-oauth]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.create-collaboration-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-social-screenshot]
verify_jwt = false

[functions.verify-publication-link]
verify_jwt = false

[functions.request-withdrawal]
verify_jwt = false

[functions.fincra-checkout]
verify_jwt = false

[functions.fincra-webhook]
verify_jwt = false

[functions.fincra-verify-payment]
verify_jwt = false

[functions.fincra-payout]
verify_jwt = false
