project_id = "fkfdjibqpmdaobjrryja"

[functions.send-auth-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.youtube-oauth]
verify_jwt = false

[functions.tiktok-oauth]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-social-screenshot]
verify_jwt = false

[functions.verify-publication-link]
verify_jwt = false

[functions.request-withdrawal]
verify_jwt = false

[functions.stripe-publishable-key]
verify_jwt = false

[functions.send-identity-rejection-email]
verify_jwt = false

[functions.send-app-download-reminder]
verify_jwt = false
